### ISSUE TITLE
Bot api server general questions

### ISSUE THREAD

**Issue by Fedorus** [tdlib/telegram-bot-api#1]
1) Is it right that this is bot-api to client-api proxy for bots? 
2) Can we extend this server api with methods that exist in client api and can be called by bots but does not exist in bot api?

**Comment by levlam** [comment]
1. Yes. And it ever was.
2. No. Bots have access only to methods required for the Bot API implementation.

**Comment by Fedorus** [comment]
This is list of methods from client api which can be called while logged in as bot: 
https://tl.telethon.dev/methods/botindex.html
And among them there is [GetFullUser](https://tl.telethon.dev/methods/users/get_full_user.html) method that does not exist in 
official bot API... but still can be used by bots...

**Comment by giautm** [comment]
Hey, Is there an docker version to deploy bot server to any cloud that support docker?

**Comment by levlam** [comment]
@Fedorus This is not true. `GetFullUser` is used for `getChat` implementation. All `UserFull` fields not included in `getChat` response are useless for bots.

**Comment by levlam** [comment]
@giautm No. You need to build the Bot API server yourself using provided build instructions to use.

**Comment by gabbhack** [comment]
What about [limits](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this) on sending messages and so on? As far as I know, the limits for bots using the client-api (telethon/pyrogram) are stricter than for bots using official bot-api. Does this depend on whether the `app_id` is "trusted"? If bot support has increased limits, will they still apply on my server?

**Comment by fskuratov** [comment]
So, briefly, as far as I understand no new methods for Bots are available? No Recent actions history, or chat members list, right? Any exclusions maybe, or someone can add them by forking and rewriting the current BotAPI server?

**Comment by levlam** [comment]
@gabbhack 

>What about limits on sending messages and so on?

Limits always was server-side and never depended on api_id or something similar. 

>As far as I know, the limits for bots using the client-api (telethon/pyrogram) are stricter than for bots using official bot-api.

This is false.

>If bot support has increased limits for my bot, will they still apply on my server?

Yes.

**Comment by levlam** [comment]
> So, briefly, as far as I understand no new methods for Bots are available?

Briefly, you can run Bot API server locally now.

> No Recent actions history, or chat members list, right? 

Yes, because that polling of those lists wouldn't work. You can't poll Recent actions for million chats in runtime. Stay tuned for the future updates, though.

> Any exclusions maybe, or someone can add them by forking and rewriting the current BotAPI server?
No, it isn't possible to add them currently.

**Comment by RememberTheAir** [comment]
> No. Bots have access only to methods required for the Bot API implementation.

Just a clarification: using any MTProto client and logging in as a bot account, the server doesn't forbid you to send a [`channels.getParticipants`](https://core.telegram.org/method/channels.getParticipants) request. A similar method is not available in the bot api, as it doesn't expose any method to fetch a chat's members list. What is currently stopping someone from forking this project and add a method to the current available methods to request the members list using tdlib's [`getSupergroupMembers`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_supergroup_members.html)? Maybe tdlib doesn't let you use such methods if you login as a bot - or underneath tdlib uses some other mtproto method that is not available to bots (so one would have to fork this project _and_ tdlib)?

**Comment by levlam** [comment]
@RememberTheAir 
Just a clarification: `getSupergroupMembers` is required for the Bot API implementation, and you can use it with filters not exposed in the Bot API. But flood limits for such usages aren't increased for bots, so you are likely to exceed them very soon.

**Comment by RememberTheAir** [comment]
@levlam ah, I see. One should expect mtproto/tdlib to accept just methods strictly required to what the bot api allows to do - `getSupergroupMembers` is required to the current set of functionalities offered by the bot API, so it's not something Telegram left out just because. Makes sense, thanks for the clarification

**Comment by funnyflowerpot** [comment]
Thanks @levlam for proving quick and helpful answers here!

**Question:** What parts of the data transfer between Telegram client, Telegram bot, and local Bot API server are going through official Telegram servers?

In the previous version of the Bot API the data flows were pretty clear to me, but now I find it more difficult to see which network host is talking to whom and when. I was searching for details or maybe something like a sequence diagram, but I couldn't find related information so far. 

I am also asking from a data privacy perspective. **So in other words:** What data (and metadata) could be still read by official Telegram servers, when a local Bot API server is used? I think including such information in the readme file of this repository would be great in terms of transparency.

**Comment by funnyflowerpot** [comment]
Here is how I understand the network communication between the relevant hosts Telegram client (C), Telegram bot (B), local Bot API server (BAS), and official Telegram servers (OTS). Is the following outline correct? If I missed a section in official documents describing this, please let me know!

1. BAS starts (no network requests here).
1. B starts and registers with BAS.
1. B tells OTS that it can be reached via BAS.
1. Using C a user attempts to start a chat with B.
1. C asks OTS for information on B.
1. OTS tells C that B's API server is BAS.
1. C sends data to BAS, BAS forwards data to B, and vice versa.

And so:

- All subsequent communication between C and B happen with BAS as a proxy. 
- C and B never communicate directly with each other. (This also was the case before local Bot API servers.)
- OTS are only needed to establish communication between C and BAS in the beginning, but not afterwards.
- OTS and BAS never communicate directly with each other.

Is this description correct? Thank you!

**Comment by RememberTheAir** [comment]
![nomacs_2020-11-04_18-25-52](https://user-images.githubusercontent.com/16143208/98145443-30bfc280-1ecb-11eb-9270-48bb1d318ad0.png)

Sorry for the low effort diagram. This is a map of how the various involved entities interact with each other. Using your abbreviations, C never directly interact with BAS (that is, the user's Telegram app never directly connects to the server where an instance of telegram-bot-api is running). All the communications goes through Telegram's servers (OTS), which forwards them to the two mtproto clients involved: the Telegram app the user C is using on its device, and the tdlib instance telegram-bot-api (BAS) is running. BAS just acts as a front-end to the Telegram API, which is way more difficult to implement than a common Rest API (which is what BAS is supposed to be - an additional level of abstraction to interact with the Telegram API as a bot account), way more familiar and friendly to developers, so it's easier to pick up

**Comment by itsMoji** [comment]
Is there anyway to get file upload/download progress?

**Comment by funnyflowerpot** [comment]
@RememberTheAir Thank you very much for the explanation! The diagram also helps a lot, particularly the details that the Bot API server is a `tdlib` client and communicates via `MTProto`. This helped me to better grasp the idea behind [tdlib](https://core.telegram.org/tdlib) and puts the benefits of a local Bot API server into perspective. Thanks again!

**Comment by micheleselea** [comment]
Whu using the bot server api locally should improve performance? There just one more layer instead to comunicate directly... I don't get why should be better instead using not api as usual.
If the architecture whould like @funnyflowerpot said There will be benefit otherwise I don't understand

**Comment by JrooTJunior** [comment]
> Hey, Is there an docker version to deploy bot server to any cloud that support docker?

https://hub.docker.com/r/aiogram/telegram-bot-api

**Comment by kolayne** [comment]
> Why using the bot server api locally should improve performance? There is just one more layer instead to communicate directly with telegram servers. I don't get why should be better instead using bot api as usual
> If the architecture whould like @funnyflowerpot said There will be benefit otherwise I don't understand

Absolutely agree.
At first, I supposed it was created to accept PRs implementing new methods or something like that from the developers using Telegram API. Then I figured out that's not an instance of what is running on the Telegram side and started thinking something similar to what @RememberTheAir has described. After reading his explanation I felt like bingo!.. But that's wrong too...

@RememberTheAir, @funnyflowerpot, could you, please, help me understand, what are the advantages of a local bot API server?

**Comment by gabbhack** [comment]
@micheleselea 
> I don't get why should be better instead using bot api as usual.

The regular bot api is also an "extra" layer between bot and Telegram servers. A local bot api can improve performance due to a low ping and an [extended limits](https://core.telegram.org/bots/api#using-a-local-bot-api-server).

**Comment by kolayne** [comment]
@gabbhack, does it mean that usual bots interact with Telegram servers via Telegram's instance of this project (global local Bot API Server?)?
Are files stored on bot API servers rather than on main Telegram servers (tdlib)? Will they send a request to my local Bot API Server each time a user wants to download a file sent by my bot?

**Comment by gabbhack** [comment]
@kolayne 
> does it mean that usual bots interact with Telegram servers via Telegram's instance of this project (global Bot API Server?)?

Yes.

> Are files stored on bot API servers rather than on main Telegram servers (tdlib)? Will they send a request to my local Bot API Server each time a user wants to download a file sent by my bot?

All files are stored on Telegram servers, not bot api server, but I think bot api can cache [[1]](https://github.com/tdlib/telegram-bot-api/blob/551103b8cda61ef548b1f7673208fbd1acee7fa4/telegram-bot-api/telegram-bot-api.cpp#L185) [[2]](https://t.me/aiogram_ru/334118) files (or something else) that the bot requested to download.

**Comment by micheleselea** [comment]
@gabbhack ok for the limitation extended with local server, but the lower ping time can be just from you and your bot api, and than you have the "ping time" between bot api server and telegram. I see only one more node that can be slow down communication, because you always speek with a bot api even in the standard configuration, but is a bot api that run on telegram server so the mtptoto communication I think it's faster than which one with local server api and telegram.
I keep thinking that is for limitation extension and not for performance reason. @levlam what do you think abouut? that whould realy improve performance? and if so why?

**Comment by gabbhack** [comment]
@micheleselea Popular bots have a problem - their servers can handle a large number of requests, but bot api sends a maximum of 100 simultaneous requests (see [setWebhok](https://core.telegram.org/bots/api#setwebhook) max_connections parameter). This causes some users to get a response from the bot later, but it's not about the power of the bot's server. Local bot api can send 100,000 simultaneous requests, which increases the bot's throughput.

These results may not be relevant, but a simple query was faster with a local server. Of course, this depends on the server location: https://t.me/aiogram_ru/334063

**Comment by micheleselea** [comment]
ok understand, because the MTProto communication between local bot and telegram bot is not limited as direct bot API are. So the local-bot-api implementation is not restricted from the point of view of maximum number of https request?

**Comment by micheleselea** [comment]
So basically the main advantage of this infrastrutture is that the conversion between HTTP BOT API and MTPROTO is done locally and than MTPROTO si used to "multiplex" the BOT API CALL in a already established channel. That way can be interesting to test...I'll try

**Comment by funnyflowerpot** [comment]
@kolayne @micheleselea [From another issue](https://github.com/tdlib/telegram-bot-api/issues/2#issuecomment-721806709):

> [A server run by means of this project] is exactly the same server as run at https://api.telegram.org.

This is where I see the advantages of a bot API server: In the [diagram above](https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-721873231) we see an official Telegram server, the bot API server and bots. If the bot API server does not run on the same host as an official Telegram server, but bot API server and bots share the same host, then network communication between network hosts does not happen over HTTP, but MTProto. Compared to HTTP the MTProto protocol is most surely providing better performance for network communication with [Telegram apps](https://core.telegram.org/tdlib) in most cases.

And as @gabbhack said web hooks for real-time communication might be a good reason for a local bot API server too. After all HTTP and in particular an additional TLS layer (HTTPS) can provide quite some overhead. Keeping this kind of communication within a host and using MTProto's (builtin) encryption can help a lot I guess.

**Comment by funnyflowerpot** [comment]
I think for certain use cases the choice of using a local API server or not is an advantage for the community. That being said, a decentralised version (as I wondered about [above](https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-721859373)), where Telegram client and bot API server bypass the official Telegram servers, might speed things further up considerably. There would be other advantages too, for example lower load of the official Telegram servers or improved data privacy by giving more control to the bot providers (there are risks too though to be fair). But I am not sure whether MTProto would support that change in network communication anyhow.

**Comment by levlam** [comment]
@itsMoji No, there is no way to provide download/upload progress for an incoming HTTP request.

**Comment by levlam** [comment]
@micheleselea @kolayne This is **exactly** the same server bots communicate with on api.telegram.org. There are no additional or removed layers.

There can be various performance improvements, that can be achieved with the local server. For example, api.telegram.org is located in the Europe, but some bots are bound to Asia or America datacenters. These bots would work much faster if switched to the local Bot API server located in the corresponding region. Another performance improvements is ability to upload and download local files. This way the files don't need to be additionally transferred over HTTP. Also, responses to webhook requests can be sent much faster to a local server, which increases theoretical webhook throughput. Despite that improvements most of the bots don't need to switch to a local server and can continue using api.telegram.org as a gateway.

**Comment by levlam** [comment]
@gabbhack `getMe` must not be used to test server performance. `getMe` is answered immediately by the server without invoking any server requests, so the test effectively measured ping time to the Bot API server.

**Comment by micheleselea** [comment]
@levlam what I want to understand is if the HTTP requests to our local bot api server are faster than requests sent directly to the api.telegram.org. I mean: suppose I need to delete 5000 messages (sometimes happen in my bot), because the delete API can be called for one message at a time, I have to do 5000 call to api.telegram.org. Sometimes I get a message that told me to wait a while because I did to much requests. Do you think that from this point of view can be better to have a local server bot api server? Do you think I can have less flood reply?

**Comment by levlam** [comment]
The HTTP requests to a local Bot API server are definitely faster than requests sent directly to the api.telegram.org. But if they are faster for X milliseconds, then requests from the local Bot API server to Telegram servers are longer for exactly the same X milliseconds for bots boud to Europe DC. There should be no difference, where the server is located, for ordinary requests.

**Comment by micheleselea** [comment]
@levlam I was thinking that the connection between local bot api server and telegram server, because is MTPROTO, is a connection already established, so there's no the handshake time (at least). Than I was thinking to the delay that api.telegram.bot introduce in serving requests and send it via MTPROTO.
Because if the connections/requests limits are the same and the only benefit is the delay time for bot outside Europe I think probably I can stay with api.telegram.org

**Comment by levlam** [comment]
@micheleselea You are right that MTProto has no handshake time at all during ordinary usage. But HTTPS connections after initial handshake can also be reused. If the connections aren't reused, then this gives another performance improvement for local Bot API server.

But most bots still don't need to use a local Bot API server, because api.telegram.org server is more than sufficient for them.

**Comment by micheleselea** [comment]
Ah ok so I can use HTTPS connection in keepalive with the server? I think was not possible

**Comment by levlam** [comment]
@micheleselea Keep-alive is irrelevant. It is enabled by default in HTTP/1.1. Instead, you should be able to use a connection pool to send HTTPS requests to the server, but ability to do this depends on your programming language and other software used to send the requests.

**Comment by micheleselea** [comment]
@levlam I understand, we use c++ and the http class we use has that function, I just called it "keepalive" because usually the HTTP method for reusing a connection, so you don't have to "reconnect" all the times, it's Connection; Keep-Alive header. I'm going to check if it's works, I thought that api.telegram.org did not support that kind of connections

**Comment by levlam** [comment]
`Connection; Keep-Alive` is deprecated since HTTP/1.1, because this is a default behavior for servers. You don't need to specify the header. Instead your client HTTP library should be able to reuse network connections.

**Comment by micheleselea** [comment]
@levlam HTTP header is `Connection: Keep-Alive` and I don't think is deprecated, and so I don't think that reuse connection is the default behavior, instead some servers DO NOT allow reusing connections. My client HTTP lib can reuse connections, but usually I have to set that behavior. Anyway that is going to be an off topic, I'll try to reuse connections to api.telegram.org that I wrongly thought was not allowed

**Comment by makisukurisu** [comment]
Even though I can modify some parameter I can't change how much data can be passed trough callback_data parameter? Or can I?

If not, will it be increased in near future?

Thanks for reply in advance.

**Comment by levlam** [comment]
>  I can't change how much data can be passed trough callback_data parameter?

You can't.

> If not, will it be increased in near future?

No. It should be as small as possible to minimize client traffic and 64 bytes is more than enough to store unique ID for a data of any size.

**Comment by gabbhack** [comment]
Why should the client see and transmit the date? Why not store the original date on the telegram server and send a minimal ID to the client? When you click on the button, the server would substitute the original date.

**Comment by jcmag** [comment]
currently bots are limited to 50MB when they send files; could we bypass this limit by running a local API server?

**Comment by RememberTheAir** [comment]
@jcmag yes: https://github.com/tdlib/telegram-bot-api#usage

**Comment by puppy0cam** [comment]
> @micheleselea @kolayne This is **exactly** the same server bots communicate with on api.telegram.org. There are no additional or removed layers.
> 
> There can be various performance improvements, that can be achieved with the local server. For example, api.telegram.org is located in the Europe, but some bots are bound to Asia or America datacenters. These bots would work much faster if switched to the local Bot API server located in the corresponding region. Another performance improvements is ability to upload and download local files. This way the files don't need to be additionally transferred over HTTP. Also, responses to webhook requests can be sent much faster to a local server, which increases theoretical webhook throughput. Despite that improvements most of the bots don't need to switch to a local server and can continue using api.telegram.org as a gateway.

Is there any way to easily determine what datacenter our bot is bound to?

**Comment by micheleselea** [comment]
ping api.telegram.com and you will see that is somewhere in Nederland.
For your bot, just look at datacenter IP where the your bot is running

**Comment by micheleselea** [comment]
@levlam about my question on "delete" requests I posted yesterday:
what I want to understand is if the HTTP requests to our local bot api server are faster than requests sent directly to the api.telegram.org. I mean: suppose I need to delete 5000 messages (sometimes happens in my bot), because the delete API can be called for one message at a time, I have to do 5000 call to api.telegram.org. Sometimes I get a message that told me to wait a while because I did to much requests. Do you think that from this point of view can be better to have a local server bot api server? Do you think I can have less flood reply?

**Comment by gabbhack** [comment]
@micheleselea https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-721820998
If I understand correctly, the limits on the local server are the same as those indicated in [FAQ](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this), because these limits are regulated by Telegram servers.

**Comment by micheleselea** [comment]
ok understand, so I think that I can keep running on api.telegram.org and I'm trying the reuse https connections

**Comment by gabbhack** [comment]
> 
> 
> ping api.telegram.com and you will see that is somewhere in Nederland.
> For your bot, just look at datacenter IP where the your bot is running

This is not about where the bot is located, but about which telegram data center it is linked to, because users from different regions are linked to different data centers. If I understand correctly, this may cause a situation when a bot linked to an Asian data center, for example, connects to api.telegram.org, which is located in Europe, and after the bot api connects to the Asian data center.

**Comment by micheleselea** [comment]
Ok but just ping api.telegram.org from location where you have bot running and you will find where your bot is connecting to

**Comment by RememberTheAir** [comment]
@micheleselea a bot using the official bot API (api.telegram.org) will _always_ connect to some Netherlands server, because this is where the api is hosted. Then the Netherlands server will connect to the user Data Center (there are 5) to pass the request to Telegram. So, let's say I'm hosting the bot in an US server, and I have to send a message to an user which has his data stored in the US datacenter - the message the bot sends from the server takes this route: US (server where the bot is hosted) -> Netherlands (api.telegram.org) -> US datacenter -> user phone. If, in this scenario, you host an intance of telegram-bot-api in an US server, you don't probably have to have your requests routed all the way to Europe, because telegram-bot-api will connect (through tdlib) to the US datacenter (via mtproto), if the bot data is stored in the US datacenter. But how do you know to what datacenter a bot is bound to? I think this is what has been asked

**Comment by Poolitzer** [comment]
> As far as I know (please someone correct me if I'm wrong), each Telegram account has its data stored in a specific datacenter, and it never migrates (or migrates only if some parameters are met, very unlikely nonetheless)

They do migrate, if their account connects consistently from a different location. If you move to Europe from the US, after some time, your account will move with you :)

**Comment by levlam** [comment]
@Poolitzer No, they don't migrate currently, but this could be implemented in the future.

**Comment by puppy0cam** [comment]
> @Poolitzer No, they don't migrate currently, but this could be implemented in the future.

Could this be implemented for bot accounts sooner rather than later? Even if we can run an instance of the bot API locally, many people may still prefer to use the official servers.
This could be a setting in BotFather to change the region our bot is located on to help migrate our bot to the region with the largest amount of our users.

**Comment by fskuratov** [comment]
> > @Poolitzer No, they don't migrate currently, but this could be implemented in the future.
> 
> Could this be implemented for bot accounts sooner rather than later? Even if we can run an instance of the bot API locally, many people may still prefer to use the official servers.
> This could be a setting in BotFather to change the region our bot is located on to help migrate our bot to the region with the largest amount of our users.

If I am not mistaken, all of the BotAPI servers are currently located in Amsterdam.

**Comment by Poolitzer** [comment]
> Could this be implemented for bot accounts sooner rather than later? Even if we can run an instance of the bot API locally, many people may still prefer to use the official servers.

For people using the cloud, it shouldn't make a difference. If I understood this correctly (apparently gotta be careful about my formulation here), all the bot API instances hosted by telegram (the cloud) are running on servers in the Netherlands. So changing the home DC of a bot wouldn't bypass the Netherlands if Telegram doesn't also provide cloud instances in places where the other DCs are. But now you are already requesting two things ;P

> This could be a setting in BotFather to change the region our bot is located on to help migrate our bot to the region with the largest amount of our users.

That would indeed work with local bot API instances, yes. For reasons pointed out further up in the thread.

**Comment by abdoo9** [comment]
how many bots I can run on the local server? I've reched 4184 and start getting this error 
```
{
  ok: false,
  error_code: 500,
  description: 'Internal Server Error: restart'
}

**Comment by Poolitzer** [comment]
As stated in #73 you should only be limited by your servers resources
