### ISSUE TITLE
Ram Consumption

### ISSUE THREAD

**Issue by ImTheDeveloper** [tdlib/telegram-bot-api#105]
Since running local bot API I'm seeing a continual increase in RAM Consumption.

Currently running through a docker container which I can easily kill and restart to drop the usage down again but wanted to know if this is a known issue and whether there are any remedies?

**Comment by levlam** [comment]
Bot API server caches information about users, chats and much more. Without such cache all requests would work much slower and popular bots wouldn't able to work at all, because they would exceed server-side flood limits. From the other side, if the bot isn't popular its cache size is very small, so it creates no issues.
