### ISSUE TITLE
Can't set gallery flag for messages.setInlineBotResults using Bot API

### ISSUE THREAD

**Issue by allerter** [tdlib/telegram-bot-api#136]
The [`messages.setInlineBotResults`](https://core.telegram.org/method/messages.setInlineBotResults) method has a `gallery` flag which can be useful, but the problem is bots can only set this flag if they're using the MTProto API. Why isn't it available through the Bot API?

**Comment by levlam** [comment]
Because there are no guarantees that this flag will be taken in account by clients. Clients have their own design for inline query results and can show them in any way they support regardless of this flag.

**Comment by allerter** [comment]
If clients have their own design for inline query results, why some other flags have been implemented in the Bot API? For example `hide_url` in [`inlineQueryResultArticle`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1inline_query_result_article.html). Couldn't clients ignore flags like these as well?

**Comment by levlam** [comment]
In Bot API you can specify parameters, which are supposed to be supported by all clients and are guaranteed to be supported by official clients. It would be bad to add parameters, which will not work anyway.

References to MTProto API are irrelevant there. For example, you can specify captions for sent stickers in MTProto API, but this doesn't mean that `caption` parameter needs to be added to `sendSticker` method, because there are no clients which will show the caption. Such a parameter would be misleading at best.

**Comment by allerter** [comment]
True, but unlike `caption`, the `gallery` flag could have a use case: what if I wanted the content to be a captioned photo, but provide titles and descriptions for the results? Right now, I use `InlineQueryResultArticle` and add the URL of the image at the end of the `InputMessageContent.message_text` to mimic a captioned photo. If I could set `gallery=False`, I would use `InlineQueryResultPhoto` and set `title`, `description`, and the message text from before in `caption`.

**Comment by levlam** [comment]
It doesn't depend on whether something is useful. It depends on whether it is guaranteed to work and is supported by all clients.

**Comment by levlam** [comment]
So, if this mode will be supported by all clients, the corresponding ability can be added to Bot API.

**Comment by allerter** [comment]
I understand now. Thanks for answering.
