### ISSUE TITLE
Forwarding media from a channel to a group results in BadRequest: The message can't be forwarded

### ISSUE THREAD

**Issue by PXNX** [tdlib/telegram-bot-api#143]
I'm using [PTB](https://github.com/python-telegram-bot/python-telegram-bot) (python Bot Api wrapper) to forward any post in a specific channel to 5 other groups like so:

`dp.add_handler(MessageHandler(Filters.update.channel_post & Filters.chat(CHANNEL_ID), forward_post))`

and then call

```
def forward_post(update: Update, _: CallbackContext):
    for i in (GROUPS):
        update.channel_post.forward(i, timeout=100000)
        time.sleep(3)
```

Unfortunately this only works for text messages and results in `telegram.error.BadRequest: The message can't be forwarded` for any other type of message.

I was told to better reach here as it seems to rather be related to Bot Api than PTB.

1) Any way to enable it for photos, videos and animations aswell?

2) Does Bot Api even support that?

**Comment by levlam** [comment]
https://core.telegram.org/bots/api#forwardmessage describes, which messages can be forwarded. Photos, videos, animations aren't service messages and can be forwarded. The issue is somewhere else.

Check permissions of the bot in the target chat and that correct parameters are passed to `forwardMessage`. If this wouldn't help, you can contact @BotSupport in Telegram for further help.

**Comment by PXNX** [comment]
Already checked the link you sent, that's what made me open this issue basically :D

The bot has full permissions and is able to foward channel posts which are text only.

**Comment by levlam** [comment]
Have you checked both permissions returned by `getChat` with the target chat and `getChatMember` for the bot itself in the target chat?
