### ISSUE TITLE
Internal Server Error on createNewStickerSet

### ISSUE THREAD

**Issue by DjMike238** [tdlib/telegram-bot-api#144]
Every time I run [this test](https://github.com/NicoNex/echotron/blob/5d6054fe6cf0e1f23d41924ae5cc896a7894cb4e/stickers_test.go#L48) (also custom method implementation [here](https://github.com/NicoNex/echotron/blob/v3/stickers.go#L128) for reference) for the `createNewStickerSet` method, I always get
```
500 Internal Server Error: created sticker set not found
```
Even if the new sticker set is created successfully, and the following tests (which add, move and delete stickers) work successfully.

The weirdest thing is, by executing the exact same request with `curl`, everything works without any issue, even if the sticker pack already exists.

I'm not really sure of what am I doing wrong, is this an issue on Telegram's end?

Thanks in advance.

**Comment by levlam** [comment]
Do you use a name of a deleted sticker set? I,e, previously there was a sticker set with the same name, which was deleted.

**Comment by DjMike238** [comment]
Yes, since I delete it everytime I run my tests, but if I don't I still get a different error, that is
```
400 Bad Request: sticker set name is already occupied"
```
which makes sense, since the sticker set already exists.

**Comment by levlam** [comment]
"500 Internal Server Error: created sticker set not found" is returned whenever you create a sticker set with a name of a recently deleted sticker set. The new sticker set can't be found by this name, because old sticker set is still found by it. The old sticker set is empty an deleted, so the error happens.

**Comment by DjMike238** [comment]
So, after 10-15 minutes after deleting the sticker set, its name should become available again, is that right?

**Comment by levlam** [comment]
Yes, some unspecified time should pass.

**Comment by DjMike238** [comment]
Got it, thanks for clarifying.

**Comment by levlam** [comment]
500 is returned because the request was correct (i.e. this isn't 400), but there is no way to return the correct sitcker set. Alternatively, 429 can be returned in this case, but it is actually unknown when a sticker set with the same name can be safely created.

Creation of sticker sets with a name of already deleted sticker set is not a recommended workflow. For example, after that links t.me/addstickers/... will point to a compeletely different sticker set and so on. Possibility to do this can be completely removed in the future.
