### ISSUE TITLE
Include used invite_link in supergroup, identical to private groups

### ISSUE THREAD

**Issue by khmikkelsen** [tdlib/telegram-bot-api#148]
Currently, when new members join a private group using an invite link, the link they used is listed under `chat_member.invite_link`

However, if the group is a supergroup, this attribute is not passed on.

Expected behavior:
`chat_member.invite_link` should be present with the used invite link regardless if the group is a supergroup or private.

**Comment by levlam** [comment]
If new member joins a public group using an invite link, then the invite link is also included in the update. You can check this by using `joinChatByInviteLink` request from TDLib. The update will have invite link regardless of the group being public or private. It is a specific app, which directly joins the public group, instead of joining it via an invite link.

**Comment by levlam** [comment]
You can try to create an issue for a specific app at bugs.telegram.org, but I don't know whether it will be addressed. If the chat is public, then user is able to join it directly and apps use this possibility as more viable.

**Comment by khmikkelsen** [comment]
> You can try to create an issue for a specific app at bugs.telegram.org, but I don't know whether it will be addressed. If the chat is public, then user is able to join it directly and apps use this possibility as more viable.

Yea okay, I get why.. For others trying to achieve the same, I have unfortunately had to resorted to creating invite links to a private group, then using this private group only to refer people to the public group.
