### ISSUE TITLE
 [Documentation] InputMedia's media field should use "InputFile or String" as type

### ISSUE THREAD

**Issue by Skayo** [tdlib/telegram-bot-api#166]
Correct me if I'm wrong, but shouldn't the `media` fields in `InputMediaPhoto`, `InputMediaVideo`, etc. all use `InputFile or String` as type?

I think it would make a lot more sense, consistency-wise.
For example in `InputMediaVideo`, `thumb` and `media` are pretty similar, but `thumb` has the type `InputFile or String` and `media` only has the type `String`?

Let me know what you think.

**Comment by levlam** [comment]
`InputMedia` is a JSON object. There is no way to embed an `InputFile` inside a JSON object. `InputFile` mention from `thumb` field description was removed.

**Comment by Skayo** [comment]
That also works for me! 😊

**Comment by levlam** [comment]
`InputFile` mention in description of the `thumb` field was added back. In fact, you can upload a thumbnail directly under field name "thumb". This is useless for `sendMediaGroup`, because you can't specify different thumbnails this way, but it can be useful for `editMessageMedia`. For the `media` fields such usage isn't allowed now even for `editMessageMedia`, therefore there is no `InputFile` in the documentation..
