### ISSUE TITLE
[req] Add latest response time into getWebhookInfo

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#195]
It would be great if you add a field for latest response info into `getWebhookInfo` in milisecond, I can see my own server responses but i can not found out how long it takes in over all, I mean:

- User sends a message
- Client make a request into mtproto
- mtproto shake bot-api shoulder
- bot-api sends a request into bot webhook (I can calculate this in my own server)
- bot api wait the webhook to finish
- bot api forwards the request into mtproto (i cannot see this how long it takes)

**Comment by levlam** [comment]
There can be thousands simultaneous requests with different duration.

Between, what do you mean by "bot api forwards the request into mtproto"?

**Comment by foremtehan** [comment]
Ignore the second part, I just want to know what is the total response time between my server and telegram when a request comes in and finishes

**Comment by levlam** [comment]
This is still not suitable for `getWebhookInfo`, because there can be a lot of simultaneous requests and even one Bot API request can lead to a lot of Telegram API requests. Also, you can easily measure total request time and ping time to the Bot API server. The latter is neglible if the bot is on the same server as Bot API server.
