### ISSUE TITLE
Too Slow Responses

### ISSUE THREAD

**Issue by alil0rd** [tdlib/telegram-bot-api#217]
First of all thanks for this repository.
I encountered a problem regarding the speed of responses to requests.
I was wondering why my bot answers requests, sometimes, with 60 seconds delay!
Could you please help me with this regard? Did I make a mistake in the bot settings? When I used api.telegram.org I didn't have any problem.
   I attached the log.
Thank you
[mylog.txt](https://github.com/tdlib/telegram-bot-api/files/7773353/mylog.txt)

**Comment by levlam** [comment]
You send HTTP requests with "Expect: 100-continue" header and expect server response with "100 continue" before continuing to send request body. You need to remove the header, because it just slows down all requests. In the case of direct requets to the Bot API server, it adds 2 seconds (timeout of your HTTP implementation) to the duration of requests.

**Comment by alil0rd** [comment]
> You send HTTP requests with "Expect: 100-continue" header and expect server response with "100 continue" before continuing to send request body. You need to remove the header, because it just slows down all requests. In the case of direct requets to the Bot API server, it adds 2 seconds (timeout of your HTTP implementation) to the duration of requests.

Thanks a million!!! You solved my issue.
