### ISSUE TITLE
"Delete Bot" and "Block Bot" gave us same updates

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#225]
![image](https://user-images.githubusercontent.com/53290883/149100350-500a5b43-23fd-4971-9a32-6b9757cec038.png)

When the user "Delete Chat" as you can see in the image, We will get this update:

my_chat_member > new_chat_member > status > kicked

The same goes when user Block the bot.

So we cannot determine if user actually blocked or deleted chat...

I think the word "deleted" is better than "kicked" and gave us better decision

**Comment by RememberTheAir** [comment]
When an user deletes a chat with a bot, Telegram blocks it. You can try the following:
1. start a chat with your bot
2. delete the chat with the bot from a Telegram app
3. make the bot send a message to the user
The API will raise an exception, because the bot was blocked by the user. In fact, when you delete the chat from the Android app, it says "_do you want to delete the chat with {bot name} and lock it?_"
