### ISSUE TITLE
Add arch linux install instructions.

### ISSUE THREAD

**Issue by max-ishere** [tdlib/telegram-bot-api#248]
The installer [instructions](https://tdlib.github.io/telegram-bot-api/build.html) don't mention arch linux.

There is an AUR package for avaliable: `telegram-bot-api`. Here are the installation instructions:

```shell
yay -S telegram-bot-api
```
(Then just hit enter a couple times)

-----

2 packages avaliable on the AUR:

aur/[telegram-bot-api-git](https://aur.archlinux.org/packages/telegram-bot-api-git) 5.7-1 (+0 0.00)
    Telegram Bot API server

aur/[telegram-bot-api](https://aur.archlinux.org/packages/telegram-bot-api) r98.81f2983-1 (+1 0.00)
    Provides an HTTP API for creating Telegram Bots.

-----

Tested on Manjaro Linux.

**Comment by levlam** [comment]
https://tdlib.github.io/telegram-bot-api/build.html contains build instructions for different operating systems and distros, and `telegram-bot-api` is a ready to use AUR package containing the build instructions from the link. The package can be used instead of the raw build instructions, but it doesn't replace them.
