### ISSUE TITLE
Client authentication in webhook mode

### ISSUE THREAD

**Issue by MikailBag** [tdlib/telegram-bot-api#252]
Hello. We have a bot, and we would want it to use webhook mode instead of long polling. However we are currently concerned that it is hard to determine if the incoming request is legitimate (sent by Telegram API) or not (sent by hacker who knows IP adress of our webhook server).

As far as I understand, we have only two options available right now:
1. Embed some secret value into URL.
1. Verify client IP address.

The first approach is pretty insecure - it is hard not to leak token due to a timing attack, or in the request log.

The second approach is much better, but IP is vulnerable to low-level transport attacks, and we would like to defend against them too.

To achieve full security, I propose to add some means of authentication support to webhook mode. It may be TLS client certificate, HMAC signature based on request payload or any other kind of authentication.

If you agree that client authentication is useful, I am ready to implement it and send pull request.

Please note that we use public telegram-bot-api instance, not local. I still open this issue here because, AFAIU, they share the same code base and any enhancement added to this repository will eventually appear in `api.telegram.org` too.

**Comment by nmlorg** [comment]
Are you concerned exclusively about your own bot, or that it's [too] easy for other people to improperly secure their bots?

**Comment by MikailBag** [comment]
Yes, our primary concern is our bot. We want it to be secure against as many attacks as possible, but without using complex architecture like managing local `telegram-bot-api` instance.

**Comment by nmlorg** [comment]
> it is hard not to leak token due to a timing attack

If your webhook is `https://example.com/mybot/110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw`, and you route all requests to `https://example.com/mybot/*` to your handler, then capture the `"110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw"` and compare it to your current token using a [constant-time algorithm](https://en.wikipedia.org/wiki/Timing_attack#Avoidance) (like [`hmac.compare_digest`](https://docs.python.org/3/library/hmac.html#hmac.compare_digest)), does that meet your needs?
&nbsp;

>  or in the request log.

Can you restrict access logs to people who already have access to the bot's token?

Are there other issues you're concerned with?

**Comment by levlam** [comment]
@MikailBag
> The first approach is pretty insecure - it is hard not to leak token due to a timing attack, or in the request log.

I would say that it is really hard to leak the token due to timing attacks if you are concerned about them. For example, @nmlorg suggested an absolutely secure way to mitigate timing attacks. Also, if an intruder can read files on your server, for example, request log, then your security is already compromised.

You can also use IP range check as additional security measure, so only a provider-wide intruder can try to attack you.

> If you agree that client authentication is useful, I am ready to implement it and send pull request.

I don't think that client authentication is useful, because there are simpler and more efficient solutions. If you think that you can't protect the secret URL path from leaking, then switching to a local Bot API server is a reasonable security measure. Also, you can continue to use `getUpdates`, which has no downsides compared to webhooks.

**Comment by MikailBag** [comment]
Thanks for your comments. Thinking about it more, I agree that checking both secret and source is secure enough.
