### ISSUE TITLE
Add attach:// input string for setWebhook

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#259]
The `certificate` param only accepts InputFile, not the attach link. According to https://github.com/tdlib/telegram-bot-api/issues/167#issuecomment-899001513, it should work for all methods.

**Comment by Bibo-Joshi** [comment]
Thanks for your comments both here and on #167. Let me ask some follow up questions for clarifying/double checking:

* Are there any other parameters accepting `InputFile` where `attach://` does not work?
* Will future methods accepting `InputFile` parameters also support `attach://`?
* I understand https://github.com/tdlib/telegram-bot-api/issues/259#issuecomment-1104129241 as that you'd prefer libraries to not use `attach://` unless it's documented - is that impression correct?

Your feedback would be greatly appreciated!

**Comment by WaffleLapkin** [comment]
> But it is bad, that I explicitly allowed to use this intentionally undocumented behavior and some popular Bot API libraries now use it for all file downloads, which could have resulted in non-working certificate upload.

They are using `attach://` because sometimes it simplifies everything a great deal. Since it is used in "popular Bot API libraries" anyway, wouldn't it be better to just implement it for all methods (it shouldn't be that hard, since most methods already support it?) and document that it's actually allowed?

It's sad that undocumented behavior leaked into the public and is now being used, but it seems like at this point it would be more beneficial to just allow it.

**Comment by levlam** [comment]
> Are there any other parameters accepting InputFile where attach:// does not work?

For now only `certificate` parameter in `setWebhook` doesn't allow `attach://` indirection.

> Will future methods accepting InputFile parameters also support attach://?

They will support `attach://` if there could be multiple files simultaneously uploaded. Otherwise, the answer is unknown.

> that you'd prefer libraries to not use attach:// unless it's documented - is that impression correct?

I prefer libraries to use documented features. but I have no plans to break `attach://` support in the methods in which it currently accidentally works.

> and document that it's actually allowed

This is the hardest part. InputFile documentation is already a mess.

**Comment by Bibo-Joshi** [comment]
> I prefer libraries to use documented features.

Understandable. That's what we're rolling back to.
Thanks again for your comments!

**Comment by Poolitzer** [comment]
Topic seems discussed at length to me, closing.
