### ISSUE TITLE
Abililty for bots to react to messages

### ISSUE THREAD

**Issue by ramonsmits** [tdlib/telegram-bot-api#260]
It would be nice if the API allows bots to react to messages. Unfortunately, bots can only "reply". Ability to react would be a create way for bots to respond and keep the chat clean and tidy.

**Comment by L422Y** [comment]
+10 … Crazy that this isn't a core feature!

**Comment by erfanmola** [comment]
> It would be nice if the API allows bots to react to messages. Unfortunately, bots can only "reply". Ability to react would be a create way for bots to response and keep the chat clean and tidy.

It would be meaningless that a bot reacts to a user's message, this usually has to be the other way around

**Comment by L422Y** [comment]
> It would be meaningless that a bot reacts to a user's message, this usually has to be the other way around

It would not be meaningless, maybe in your use case is what you meant?

For instance, I need a bot to be able to mark a message as seen / processed and I don't want a bunch of text messages from the bot just for emoji responses.

**Comment by ramonsmits** [comment]
A bot can reply to e regular message. It would make sense it can react too.
Keeps acknowledging tidy.

**Comment by aditya-yadav-27** [comment]
for reference you can also upvote this --> https://bugs.telegram.org/c/12710

**Comment by Futurixel** [comment]
No news about this ?

**Comment by foremtehan** [comment]
My only use case about reactions is, being able to get update when user react to some message or get total number of reactions.

**Comment by Danstiv** [comment]
My use case:
I'm making a bot that will allow to convert text documents into audio files using a speech synthesizer.
The bot will have a main menu with settings and a queue.
In the settings, it will be possible to configure the synthesis parameters, and in the queue to track the status of the conversion.
To convert a document, the user will have to send a text file / url to a file / archive with files, etc.
And it would be incredibly convenient if my bot just marked the message sent by the user, say, with a thumbs up.

**Comment by KasperGreen** [comment]
My example is a rating of users by message reactions.

**Comment by muzmich** [comment]
+1
I am writing group chat bot, and feature which allows to mark participants messages would be very useful.

Also, would be nice, to have an ability to do something with messages, depending on reactions it has.
e.g if message has more than 10 dislikes - remove it

**Comment by NastassiaD** [comment]
+1
I am waiting for this feature so hard.

**Comment by namen3645** [comment]
+1 this is very need function

**Comment by qadirsuh** [comment]
Very good feature request! I also need this feature in my case.
@Auther @TelegramOwners @BotFather any ETA for this?

**Comment by AYMENJD** [comment]
@qadirsuh There is no eta.

**Comment by qadirsuh** [comment]
We want this amazing feature please do take care of developers democracy :D

**Comment by RememberTheAir** [comment]
In a post about reactions you would expect people to actually use them to express their support instead of pinging everyone with messages that boils down to "yeah i want that too" :P

**Comment by ramonsmits** [comment]
Keep upvoting on the official API! https://github.com/tdlib/telegram-bot-api/issues/260

**Comment by mhryshkin** [comment]
Such a desirable feature to have within bot API

**Comment by syabro** [comment]
It's a must!

**Comment by asksock** [comment]
Yep, upvote again 😂

**Comment by iamsoorena** [comment]
Use case:
You have two bots; one rates the other by reacting to its messages.

It's a must.

**Comment by k1ryl** [comment]
Up

**Comment by vladimirkus** [comment]
up

**Comment by tapochqa** [comment]
upupupupup

**Comment by whitepapercg** [comment]
UP

**Comment by freehuntx** [comment]
I also need this feature

**Comment by bessudnov** [comment]
Up 👍

**Comment by livxy** [comment]
Can you guys, please stop bumping this thread? It's already public enough, and it's just another notification that gets spammed in everyone's inbox. There's a reason for up-voting.

**Comment by tapochqa** [comment]
> Can you guys, please stop bumping this thread?

no

**Comment by k1ryl** [comment]
bump it mfs!

**Comment by ramonsmits** [comment]
Please don't do auch childish responses otherwise they likely lock issue.

**Comment by gaparchi** [comment]
Up!

**Comment by PlebeiusGaragicus** [comment]
> +1
> I am waiting for this feature so hard.

Came here hoping this feature existed... will wait for it and be disappointed until it's realized.

I'm writing a chatbot using OpenAI's API.  I'm doing several layers of prompts in order to parse user messages and formulate a reply.. I'm trying to think of ways of letting the user know that the bot is "typing" or otherwise formulating a reply because it takes 20-30 seconds.  A 'tap-back' emoji reply would be really useful.  I can't get the "typing" chat action to work thus far.

**Comment by sutyrin** [comment]
> I can't get the "typing" chat action to work thus far.

Yeah, typing notification should work well, it is specifically designed for that purpose.

**Comment by olegon-ru** [comment]
I would like to alert near limit message toxicity by reaction...

**Comment by DAcKeyy** [comment]
бамп

**Comment by guilatrova** [comment]
up

**Comment by mrskrsm** [comment]
this sounds interesting, I hope this feature will eventually be implemented in the API

**Comment by Volftsun** [comment]
UP!

**Comment by gagafonov** [comment]
UP!

**Comment by BlueberryCat0** [comment]
Up!

**Comment by livxy** [comment]
> Up!

can you not?

**Comment by yeysman** [comment]
Any updates? 👀

**Comment by Jessica0813** [comment]
up

**Comment by Ryce** [comment]
We need this one as well. Whats the ETA on this?

**Comment by Abdulloh8** [comment]
Up

**Comment by BugDeveloper** [comment]
Up

**Comment by alshuriga** [comment]
Up

**Comment by Euro-pol** [comment]
Up

**Comment by maccman** [comment]
Up

**Comment by ElisaMin** [comment]
i want this too

**Comment by proxeter** [comment]
Very useful feature! Up

**Comment by viktor76525** [comment]
A nowhere near as good alternative for the (near) instant acknowledgement use case is to send a chat action.

**Comment by andrey-helldar** [comment]
@viktor76525 Yes, but you forgot to look from the other side. For example, when a spammer enters the chat, but they don’t want to ban him because... this will reduce the number of group members. Instead, he is given a permanent mute. And at this moment this spammer begins to send reactions to all messages in a row. I've encountered this before. And at the moment there is only one method of fighting - to send him to a ban by losing one chat participant in the statistics.

**Comment by RememberTheAir** [comment]
@andrey-helldar how would letting bots react to messages help with that?

**Comment by andrey-helldar** [comment]
@RememberTheAir In this particular case, it will be possible to improve the spam detection system. For example, when someone starts adding reactions to a large number of messages in a short period of time.

**Comment by spuro** [comment]
give me bot reactions or give me death

**Comment by nillkitty** [comment]
Hi;  we need this.  It's a valuable tool in determining how human an account is,  as Telegram scales,  it is becoming increasingly harder and hard to tell who is real and who is a scammer,   who is legit and who is a troll.   One politically-agnostic and democractic way to solve this is to allow unknown users to participate in the chat for as long as validated users are reacting positively to their messages.   Reacting to someone's messages occurs automatically,  is already inherently limited to one-emote-per-user-per-message by the system,  and would be invaluable in gauging how valid/valuable/acceptable the general user base finds a given message, set of messages, or a user's behavior in general.   

I use bots to prevent scammers and other bad actors from scamming innocent people in public chats related to conventions and other events where there is often the ability to pray on desperate folks needing a room/ride (since most of these events are limited capacity and book attendees by lottery).

**Comment by kc97ble** [comment]
we need this T.T

**Comment by egorperesada** [comment]
Confirmed, we need this

**Comment by BonifacioCalindoro** [comment]
Ultra confirmed, this is needed!

**Comment by ivanvorobei** [comment]
good to have it

**Comment by clot27** [comment]
Rather than spamming "up" and similar comments, just react with :+1: to show your agreement.

**Comment by Danstiv** [comment]
https://core.telegram.org/bots/api-changelog#december-29-2023

Perhaps now the issue can be closed.

**Comment by ramonsmits** [comment]
> [core.telegram.org/bots/api-changelog#december-29-2023](https://core.telegram.org/bots/api-changelog#december-29-2023)
> 
> Perhaps now the issue can be closed.

Maybe:

Added the method [setMessageReaction](https://core.telegram.org/bots/api#setmessagereaction) that allows bots to react to messages.

https://core.telegram.org/bots/api#setmessagereaction

**Comment by ramonsmits** [comment]
This commit is referencing the API https://github.com/tdlib/telegram-bot-api/commit/0ec870fd77a97da9a532a8c80add073c1a56d2fd
