### ISSUE TITLE
Bot API 6.0 Changelog doesn't mention renaming of `VoiceChat*` classes

### ISSUE THREAD

**Issue by Bibo-Joshi** [tdlib/telegram-bot-api#263]
They are now named `VideoChat*`. This more or less implicitly clear because the corresponding attributes of `Message` where renamed, but IMO it would be good to add it to the changelog nonetheless.

**Comment by levlam** [comment]
This change is a documentation-only change. Class names aren't used in object serialization, and hence they didn't affect interaction with Bot API in any way. Documentation changes with no actual changes aren't duplicated in the change log.

**Comment by Bibo-Joshi** [comment]
Fair enough. I would have expected it since e.g. the API 5.3 changelog explicitly mentioned the change in the `ChatMember` classes. Anyway, I'll go ahead and close. Thanks for the reply!

**Comment by levlam** [comment]
`ChatMember` documentation change was mentioned, because I wanted to attract attention to this. It was a common misunderstanding, that all fields of `ChatMember` can be used for all chat member types. The change log entry explicitly says that it was a documentation-only change, and nothing actually changed.

For example, when `ReplyKeyboardHide` was renamed to `ReplyKeyboardRemove`, only corresponding field name change was added to the Change Log.
