### ISSUE TITLE
Can't build because FlatHashMap.h is not found

### ISSUE THREAD

**Issue by uhfath** [tdlib/telegram-bot-api#296]
Building on Ubuntu 20.x using clang with instructions from generator.
Got this error:
```
/home/administrator/telegram-bot-api/telegram-bot-api/Query.h:18:10: fatal error: 'td/utils/FlatHashMap.h' file not found
#include "td/utils/FlatHashMap.h"
```
Checked the source and it seems that while `FlatHashMap.h` is searched in `td/utils` it is actually in `td/tdutils/td/utils`
Could it be something with CMAKE paths?
Or is it my setup?

This server was never used for anything else (i.e. no extra stuff installed).
Half a year ago when I built the API server it all went fine.
Currently wanted to updated it and this came up

Attached CMakeCache just in case.
[CMakeCache.txt](https://github.com/tdlib/telegram-bot-api/files/9065217/CMakeCache.txt)

**Comment by hesammax** [comment]
از گوشی هوشمند Samsung Galaxy ارسال شده است.
-------- پیام اصلی --------از: Kasbolat Kumakhov ***@***.***> تاریخ: ۲۰۲۲/۷/۷  ۱۹:۵۳  (GMT+03:30) گیرنده: tdlib/telegram-bot-api ***@***.***> گیرنده کپی: Subscribed ***@***.***> موضوع [tdlib/telegram-bot-api] Can't build because FlatHashMap.h is not found (Issue #296) 
Building on Ubuntu 20.x using clang with instructions from generator.
Got this error:
/home/administrator/telegram-bot-api/telegram-bot-api/Query.h:18:10: fatal error: 'td/utils/FlatHashMap.h' file not found
#include "td/utils/FlatHashMap.h"

Checked the source and it seems that while FlatHashMap.h is searched in td/utils it is actually in td/tdutils/td/utils
Could it be something with CMAKE paths?
Or is it my setup?
This server was never used for anything else (i.e. no extra stuff installed).
Half a year ago when I built the API server it all went fine.
Currently wanted to updated it and this came up
Attached CMakeCache just in case.
CMakeCache.txt

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>Hi, I'll give you a method that you won't teach anyone. Well, first, type the sentences of my server IP and write the word 77087709, everything will be fine.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/tdlib/telegram-bot-api/issues/296",
"url": "https://github.com/tdlib/telegram-bot-api/issues/296",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by uhfath** [comment]
> Did you update submodules after pulling the latest source code?

That was it!
Thank you!
I actually wasn't aware of this git nuance. Thought that submodules are update automatically.
