### ISSUE TITLE
sendMediaGroup fails when sending multiple videos without audio track

### ISSUE THREAD

**Issue by davidebeatrici** [tdlib/telegram-bot-api#315]
POST request to `https://api.telegram.org/bot<token>/sendMediaGroup`:

```json
{
	"chat_id": "<id>",
	"media": "[{\"type\":\"video\",\"media\":\"https://softether.download/test/clock_1280x720_120fps.mp4\"},{\"type\":\"video\",\"media\":\"https://softether.download/test/clock_1280x720_120fps.mp4\"}]"
}
```

Response:

```json
{
	"ok": false,
	"error_code": 400,
	"description": "Bad Request: failed to send message #1 with the error message \"Wrong file identifier/HTTP URL specified\""
}
```

No problems at all when sending a single video (which shows up as a GIF in clients). On that note, according to the [method documentation](https://core.telegram.org/bots/api#sendmediagroup):

> A JSON-serialized array describing messages to be sent, must include 2-10 items

Which doesn't seem to be the case as a single item is happily accepted.

The issue may be related to the `animation` type not being supported for media groups:

```json
{
	"ok": false,
	"error_code": 400,
	"description": "Bad Request: type \"animation\" can't be used in sendMediaGroup"
}
```

Ideally videos should always be treated as such though, the inconsistency is especially evident when sending WEBP files: if without an audio track they're treated as a GIF, otherwise as a document.

**Comment by levlam** [comment]
See https://github.com/tdlib/telegram-bot-api/issues/301.

**Comment by davidebeatrici** [comment]
Sorry, missed that.

I agree with @Poolitzer: the root issue is the Telegram backend treating videos without an audio track as animation, even when not explicitly asked to do so ([`sendAnimation`](https://core.telegram.org/bots/api#sendanimation)).

**Comment by levlam** [comment]
> One URL = one file. There is no way the file can be treated differently, no matter how you try to send it. You have an issue, because you are trying to use a URL to an animation instead of a video URL.

**Comment by davidebeatrici** [comment]
It's the distinction between `animation` and `video` based on the presence of an audio track that doesn't make sense, in my opinion.

I understand the usefulness behind the `animation` type, but I believe the choice whether to use it (instead of `video`) should be up to the API user.

**Comment by levlam** [comment]
There is a URL. There are no users involved.

**Comment by Poolitzer** [comment]
I will try to explain it since I was mentioned anyway. Telegram does not care which API method sends it an URL. It queries/downloads the URL, decides which type it is (in this context important: Animation or Video), and then passes this on to the API. So the download happens independent from the invocation method.

Media groups can not consist of animations, so if an URL links to an animation, you can not put it into a media group, or rather, the API will return an error that an invalid file type was put in the media group.

There is no way of letting the "API user" decide the file type without making huge changes to the back end, first allowing the telegram API to override the file type detection of the URL, then also implementing this into the bot API. While it would be convenient for us, it would be a lot of work for telegram, so I can very much understand them not implementing it.

**Comment by davidebeatrici** [comment]
Thank you for the detailed explanation, I understand the reasoning behind the behavior now.

At this point the question would be: does it actually make sense to consider MP4 videos without an audio track `animation` rather than `video`?

**Comment by levlam** [comment]
> At this point the question would be: does it actually make sense to consider MP4 videos without an audio track animation rather than video?

Otherwise, you wouldn't be able to upload MP4 animations via URLs at all.

**Comment by davidebeatrici** [comment]
Correct, is there a need for that though? I mean, true "animations" are usually in WEBP or GIF format.

**Comment by levlam** [comment]
GIF is a highly ineffective format with bad image quality. Most modern animations are in video formats like MP4 or WEBP.

**Comment by davidebeatrici** [comment]
Right. Considering that WEBP is quite common (and still spreading), I think we should default to `video` for MP4.

This would be a feature request at this point, as we agreed the behavior I encountered is not a bug.
