### ISSUE TITLE
Customizing amount of timeout for local servers

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#341]
Is it possible for you to add a option for customizing longer timeout at least for local servers? The default is 30 seconds, I find myself in some situations like encoding a long video for the user need longer than 30 seconds.

**Comment by levlam** [comment]
I'm not aware of any 30 second timeouts. What timeout are you talking about?

**Comment by foremtehan** [comment]
I mean when you receive a update from a webhook, If you does not response code 200 for 30 seconds, The server try to re-send the update (about 5 times i think) So i just wanted to know is it possible to increase this timeout for the above reason?

**Comment by levlam** [comment]
The timeout is 60 seconds and it is a very bad idea to increase it. Webhook requests must be answered as fast as possible to make webhooks reliable and performant. Instead of timeout increase the updates must be processed asynchronously. You need to add the update to a local message broker, confirm its receiving and process the requests by pool of workers, fetching them from the message broker.

**Comment by nezort11** [comment]
This is true, after 60 seconds Telegram bot server will mark this update as error `last_error_message: 'Read timeout expired'` in webhook info

https://stackoverflow.com/questions/44950295/encountering-read-timeout-expired-error-by-webhook-after-60-sec-of-execution
