### ISSUE TITLE
Geolocation cordinate decimal precision

### ISSUE THREAD

**Issue by busslina** [tdlib/telegram-bot-api#380]
Hello, using a Telegram Bot (https://github.com/DinoLeung/TeleDart) I realised that when sending live location via Bot sometimes I was receiving 400 Http status code with this message: `400 Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message`. 

I did my code in order to not edit location message if new coordinate was the same. So I realised that new coordinate was not exactly the same, it was different maybe from 5th or 6th decimal position, but Telegram backend was still sending that error message. Now I'm testing with only four decimal number and seem to be working okay. I found that with 4 decimal position I have a 11 meters precision aprox. I want to know what is the Telegram implementation details about this issue. It would be great to be able to have a 5 decimal precision....

Thanks

Edit: With precision I'm not saying that Telegram do not allow to send more than 4 decimal numbers of precision, I'm saying that when editing location message with new position, if new location differs from previous one only after the 4th decimal number, Telegram is saying that new location is the same that previous one, and it is sending that 400 Http error

**Comment by levlam** [comment]
Longitude and latitude can be rounded by the server, but the location shouldn't move more than 1 meter after that even if it was on the Equator.

It is recommended to call `editMessageLiveLocation` only if the location has changed by 10+ meters, or enough time has passed since the previous call to `editMessageLiveLocation`. Alternatively, you can just ignore the error.
