### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by yagop** [tdlib/telegram-bot-api#412]
I'm interested in running integration tests against this library but seems that's not possible.

May you enable any way to integrate with this API or provide a generated schema from the sources?

**Comment by levlam** [comment]
There is no way to test API provided by the Bot API server without excessive network interaction with Telegram servers. Tests which can fail any time because of network issues or remote datacenter issues aren't reliable, so there is no much sense to do them. There is no official machine-readable scheme for the API either.

**Comment by yagop** [comment]
That's a bit awful as to integrate with this library (and Telegram in general).

I was thinking if it's possible to mock the network layer but seems too complex.

Thanks for the reply 🙇

**Comment by Forden** [comment]
You can try using Telegram test environment for tests. But unreliable network will still be an issue.
