### ISSUE TITLE
Too late to send a message

### ISSUE THREAD

**Issue by AC-Lover** [tdlib/telegram-bot-api#420]
Hi
What is the problem with a simple `sendMessage` that takes about 1 second?

https://github.com/tdlib/telegram-bot-api/assets/49290111/eecf2ccc-7220-4279-b7b4-b388d941dde8

The problem only exists in long texts
And the short text, as you can see, is fine.

When this happened, when I use the telegram bot api local endpoint, but when I use https://api.telegram.org, it takes less than 100 milliseconds for telegram to respond.
So I don't think the problem is my code.

<h2>Telegram bot api log</h2>

[log.txt](https://github.com/tdlib/telegram-bot-api/files/11697361/log.txt)
https://pastebin.com/tjXdXJHH

<h2>My server profile</h2>

2 CPU cores
4 GB DDR4 RAM
80 GB NVMe SSD
Ubuntu 20

**Comment by levlam** [comment]
In the log the longest delay is between update creation at 1686266422.578 and receiving of `sendMessage` request 1 second after at 1686266423.580. Log with verbosity level at least 4 is needed to see more details about delivery of the update, but it is very unlikely that the issue is related to the Bot API server.
