### ISSUE TITLE
Higher latency of around 7 mins

### ISSUE THREAD

**Issue by garvit170** [tdlib/telegram-bot-api#422]
We have a telegram bot getting updates using webhooks. We are experiencing high latency issues where we get updates with a delay of 7 minutes sometimes. 
We tried to debug on our side and we saw there were 3500 pending updates while getting webhook info. Can you please help us identify what can be causing this or how to resolve this?

**Comment by levlam** [comment]
`getWebhookInfo` returns among other fields an error, which caused updates delivery failure.

**Comment by levlam** [comment]
Your webhook returned an error instead of updates processing. If last error date is increasing, then the webhook still doesn't work and the number of pending updates is expected to grow. When webhook works, all pending updates are expected to be handled by it after some time if the webhook is performant enough. The big number of pending updates indicates that there is no issues on the Bot API side.

**Comment by garvit170** [comment]
but I can't find any errors on my logs. Further can explain what does the webhook needs to return?

**Comment by nipunaror** [comment]
@levlam One last question here , if our server sends out a lot of 403s will telegram reduce the rate at which it delivers the webhook ?

**Comment by levlam** [comment]
Yes, if the server continues to send errors in response to webhook, then updates rate can be decreased until the server is fixed.

**Comment by nipunaror** [comment]
Thanks a lot for the quick support .

Sorry one more thing , what does 'Wrong response from the webhook: 403 Forbidden' mean ? As in what cases does the telegram webhook relay show this ?

**Comment by levlam** [comment]
It means that the webhook responded with error code 403 and error description "Forbidden".

**Comment by levlam** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
