### ISSUE TITLE
telegram-bot-api: Can't parse "6557184321" as an integer

### ISSUE THREAD

**Issue by zhuxu** [tdlib/telegram-bot-api#453]
when i run this "./telegram-bot-api --api-id=$TELEGRAM_API_ID --api-hash=$TELEGRAM_API_HASH --local" in terminal, get this error
why?

**Comment by levlam** [comment]
You specify an invalid parameter value in some request and receive the error for the request.

**Comment by mostafa-norouzi** [comment]
So why the message is irrelevant!?

**Comment by rmykland** [comment]
This error is relevant because telegram-bot-api then exits as this is apparently a fatal error. It comes up when you try to run telegram-bot-api as a local server using an API_ID and API_HASH recently supplied by BotFather. From people's notes, it appears that API_ID used to be smaller than a uint32, but now it's bigger. My guess is that the telegram-bot-api hasn't been kept up to date to allow for this. So, basically, this means telegram-bot-api is useless, at least as a local server. I'm going to look into where this is happening in the code and see whether it is reasonably fixable without being a telegram insider.

**Comment by rmykland** [comment]
The code looks surprisingly okay, and should handle an integer this large, but it just doesn't. I confirmed that this problem was integer size related by snipping the top digit off of my TELEGRAM_API_ID, and lo and behold, the server launches without error. The ID is never going to match the hash, so my bot can't be authorized, but it launches. Unusable.

**Comment by rmykland** [comment]
Anybody out there have an ID and hash pair where the ID is less that uint32? It doesn't have to be a real forever ID and hash. This is just for testing.

**Comment by rmykland** [comment]
Okay, I figured this out. The API ID and hash pair have to be issued by the telegram app configuration page https://my.telegram.org/apps. These numbers are small enough, and they work. For the bot, it's a different pair: a regular bot ID and hash pair issued by BotFather.

**Comment by rmykland** [comment]
Does it count as a documentation bug to not cover this? I think so. My only resort was trial and error.

**Comment by levlam** [comment]
@rmykland
When you run the Bot API server, it prints documentation for all supported options.
"api-id" is documented as "application identifier for Telegram API access, which can be obtained at https://my.telegram.org (defaults to the value of the TELEGRAM_API_ID environment variable)".
