### ISSUE TITLE
HELP WITH TELEGRAM-BOT-API

### ISSUE THREAD

**Issue by hatikoX** [tdlib/telegram-bot-api#569]
Hello, I want to do bot who can accept files larger than 20mb.I read documentation, but I don't understand how use this telegram-bot-api. If someone can explain or give me manual  with examples

please

**Comment by levlam** [comment]
You will have an executable file after following https://github.com/tdlib/telegram-bot-api?tab=readme-ov-file#installation.

Then, you can run the executable on your server as described in https://github.com/tdlib/telegram-bot-api?tab=readme-ov-file#usage.

Then, you can send request to http://localhost:8081 instead of https://api.telegram.org, and if the server is run in local mode, then it will be able to download files of any size.

**Comment by hatikoX** [comment]
I print in terminal: Telegram-bot-api --api-id=myid --hash-id=myhash --local

But when i sent this terminal the terminal is silent but it’s clear that the process has started, I tried to send a file larger than 20 MB after that, but the bot also crashed with error 400. Maybe I need to change something with the code?

**Comment by levlam** [comment]
You must sent requests to to http://localhost:8081/ instead of https://api.telegram.org/.

**Comment by hatikoX** [comment]
How to do it?
