### ISSUE TITLE
how to show logs?

### ISSUE THREAD

**Issue by centralhardware** [tdlib/telegram-bot-api#74]

**Comment by levlam** [comment]
What do you want to show?

**Comment by glococo** [comment]
I am migrating a Youtube channel to a Telegram Channel, so when I start uploading those videos through a bot, somehow every 2 or three videos it hangs and freeze waiting for 

I would like to learn where the bug is,
Is it a telegraf.js bug, a nodejs bug or in the localserver ?

Note that I have no hangs with the public bot server, but just with the local one, and I need it because many videos are in size higher than the max public bot server allowed.  

Thanks for your help

**Comment by levlam** [comment]
@glococo Use `--help` option to see list of all available options. Some of them can be used to control logging behavior.

**Comment by glococo** [comment]
I think this is a telegrafjs issue with local server.
https://github.com/telegraf/telegraf/issues/1301

Close the ticket. Thanks
