### ISSUE TITLE
deleteMessage not throwing error if message is already deleted 

### ISSUE THREAD

**Issue by infinite4evr** [tdlib/telegram-bot-api#94]
#### Description
 When sending a request to delete a message from a channel, with a bot having appropriate permissions, it would not throw an error even if the message_id does not exist in the chat and it was already deleted by a channel admin

#### How to reproduce? 

You need a bot with delete permissions on a channel.

1. Send a message to your channel `https://api.telegram.org/bot{token}/sendMessage?chat_id=@channel_username&text=hello`
2. Note the `id` of the message from the response and **manually delete the message from the channel** from your app or any telegram client ( must be an admin and not a bot )
3. Send a deleteMessage request `https://api.telegram.org/bot{token}/deleteMessage?chat_id=@channel_username&message_id={response_message_id}`

The response that you'll get 

```
{
  "ok": true,
  "result": true
}
```

Expected Response 

```
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message to delete not found"
}
```

Surprisingly once you get the "true" response, re-requesting the same function with same `message_id` returns the expected response, i.e the message does not exist. 
Also that once a message is deleted, the bots do not receive any updates regarding it since the message was created by a bot, so it's impossible for me to figure out that if a message has been deleted from a channel already.

**Comment by levlam** [comment]
The only guarantee of `deleteMessage` request is that the message is deleted after it is called. The error is optional and is returned only if the message is known to be definitely deleted.

**Comment by infinite4evr** [comment]
Thanks for the response, If this is so then it should be explicitly mentioned in the API docs so that users would know when to expect an error and when not to since we expect that errors will definitely be thrown if there's something wrong. Bot API seems to throw well-defined errors for all other functions and hence I expected it for this function too.

Also, is there a possibility in future to somehow find out if a message even exists in a channel or not give the `channel_id` and `message_id`?

**Comment by levlam** [comment]
Bot API has no documentation or any guaranteed behavior for errors. You can use error codes, but error messages and the fact that an error is returned is subject to change.

> Also, is there a possibility in future to somehow find out if a message even exists in a channel or not give the channel_id and message_id?

No, this would be a source of **a lot** of **useless** requests. Bots will need **a lot** of requests to check a lot of messages, and results of such checks immediately became **useless**, because the message could be deleted right after the response and even before the response is received by the bot.

**Comment by levlam** [comment]
@noplanman api.telegram.org uses exactly the server available in this repository.

**Comment by noplanman** [comment]
@levlam Ok, thanks for the confirmation.

Still doesn't change the issue at hand though, that the API is returning incorrect data.

Do you know if there are plans to make the error handling more usable?

**Comment by infinite4evr** [comment]
> No, this would be a source of a lot of useless requests. Bots will need a lot of requests to check a lot of messages, and results of such checks immediately became useless, because the message could be deleted right after the response and even before the response is received by the bot.

If a bot needs to have a functionality which requires us to check if a message exists or not, it's not a useless request, Why would someone even make such a request if they don't need it.

And if this cannot be made possible ( and the point that errors are not guaranteed ), this must be mentioned on the docs, current paragraph on error code 

> The response contains a JSON object, which always has a Boolean field 'ok' and may have an optional String field 'description' with a human-readable description of the result. **_If 'ok' equals true, the request was successful and the result of the query can be found in the 'result' field. In case of an unsuccessful request, 'ok' equals false and the error is explained in the 'description'. An Integer 'error_code' field is also returned, but its contents are subject to change in the future_**. Some errors may also have an optional field 'parameters' of the type ResponseParameters, which can help to automatically handle the error.

This is totally ambiguous and even misleading for the developers. The only thing that matches your first response is that the contents might change in the future. For the current issue, the request indeed was unsuccessful since the message does not exist.

**Comment by levlam** [comment]
@noplanman 

> Still doesn't change the issue at hand though, that the API is returning incorrect data.

Both responses are correct. If request is successful, then the message is deleted. Otherwise, some error happenned and message state is unspecified.

**Comment by levlam** [comment]
@infinite4evr

> If a bot needs to have a functionality which requires us to check if a message exists or not, it's not a useless request,

I described in details, why this request is useless. Its response is always outdated. Moreover, whatever you plan to do with a message, you shouldn't check in advanve whether it still exists and you need just use the request. If you really want to check message existence before deleting it, to ensure that noone deleted the message yet, you can use `forwardMessage` request for that.

> For the current issue, the request indeed was unsuccessful since the message does not exist.

Message nonexistence is a reason to fail `forwardMessage` or `copyMessage` requests, but the `deleteMessage` request succeeds if the message is already deleted. The error is sometimes returned only to help spot and fix possible bugs with incorrect requests, not because the request is incorrect.

The logic of all requests is simple:
- If an error is returned, then error message contains a description of an issue.
- If a successful response is returned, then postconditions of the method are met. For `deleteMessage` it is "the message is deleted".,

**Comment by noplanman** [comment]
@levlam I understand what you mean, but it still doesn't really make sense to me. If the message doesn't exist, the response should say that, especially since there is an error message for that exact case.

Anyway, I think what has become clear in this short discussion, is that the return values must be taken with a pinch of salt.

Thanks for shedding some light on how the internals work though 🙏
